server:
  port: 8081
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: password1
    key-alias: www.gdw888.net

jwt:
  secret: MySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKey

spring:
  application:
    name: nba-stats-tracker-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: nba-stats-tracker-web-server
          uri: lb://nba-stats-tracker-web-server
          predicates:
            - Path=/api/**
            - Path=/auth/**
          filters:
            - RemoveRequestHeader=Origin
        - id: write_operations_rate_limited
          uri: lb://nba-stats-tracker-web-server
          predicates:
            - Path=/api/**
            - Method=POST,DELETE,PUT
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                rate-limiter: "#{@redisRateLimiter}"
  redis:
    host: localhost
    port: 6379
    password: yourpassword

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

cors:
  allowed-origins: "http://localhost:3000,https://localhost:3000"
  allowed-methods: "*"
  allowed-headers: "*"

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 10000
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
  instances:
    NbaStatsTrackerRestAPIs:
      baseConfig: default
      waitDurationInOpenState: 5000

rate-limit:
  defaultReplenishRate: 1
  defaultBurstCapacity: 2