spring:
  application:
    name: nba-stats-tracker-web-server

jwt:
  secret: MySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKey

# SSL configuration
server:
  port: 8080
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: password1
    key-alias: www.gdw888.net

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


dynamo:
  tables:
    nba-active-players: nba_active_player_dev
    nba-player-info: nba_player_info_dev
    nba-player-stats: nba_player_stats_dev
