spring:
  application:
    name: nba-stats-tracker-web-server

jwt:
  secret: MySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKey

# SSL configuration
server:
  port: 8080
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: password1
    key-alias: myserver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/