spring:
  application:
    name: nba-stats-tracker-service-discovery

server:
  port: 8764

eureka:
  instance:
    hostname: www.gdw888.net
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

