apiVersion: apps/v1
kind: Deployment
metadata:
  name: nba-stats-tracker-redis
  namespace: nba-stats-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nba-stats-tracker-redis
  template:
    metadata:
      labels:
        app: nba-stats-tracker-redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: nba-stats-tracker-redis
  namespace: nba-stats-tracker
spec:
  selector:
    app: nba-stats-tracker-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP

