name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: [nba-stats-tracker-service-discovery, nba-stats-tracker-web-server, nba-stats-tracker-api-gateway]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew ${{ matrix.module }}:build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.module }}-build-artifacts
          path: ${{ matrix.module }}/build/libs/*1.0.0.jar

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        module: [nba-stats-tracker-service-discovery, nba-stats-tracker-web-server, nba-stats-tracker-api-gateway]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.module }}-build-artifacts
          path: ${{ matrix.module }}/build/libs

      - name: Run tests
        run: ./gradlew ${{ matrix.module }}:test

  build_docker:
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        module: [nba-stats-tracker-service-discovery, nba-stats-tracker-web-server, nba-stats-tracker-api-gateway]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.module }}-build-artifacts
          path: ${{ matrix.module }}/build/libs

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker images
        run: |
          cd ${{ matrix.module }}
          docker build -t gdw888/${{ matrix.module }}:latest .

      - name: Push Docker images
        run: |
          docker push gdw888/${{ matrix.module }}:latest
